### ISSUE TITLE
Irrelevant information on the profile page

### ISSUE THREAD

**Issue by Pinkvinus** [PhilipFlyvholm/learnit-plus-plus#10]
As of now there is a time edit schedule and student council events on the profile page.

![image](https://github.com/PhilipFlyvholm/learnit-plus-plus/assets/74830754/b1ea7764-d8cc-4677-894f-2322da8d7817)
![image](https://github.com/PhilipFlyvholm/learnit-plus-plus/assets/74830754/e1b25f26-fa81-48c1-8f92-9935a2e3a15c)
![image](https://github.com/PhilipFlyvholm/learnit-plus-plus/assets/74830754/f2621991-07b9-4bdf-a4fd-cc303056a4df)

**Comment by PhilipFlyvholm** [comment]
This is fixed in the latest commits (#6)
