### ISSUE TITLE
Messages should be sent when pressing the Enter key

### ISSUE THREAD

**Issue by PhilipFlyvholm** [PhilipFlyvholm/learnit-plus-plus#11]

**Comment by PatrickMatthiesen** [comment]
It might be a better idea to make ctrl+enter send the message, otherwise we need to make sure that shift+enter adds a new line

**Comment by PhilipFlyvholm** [comment]
Would probably be better since we may cause unintended messages if it is only entered, however, this is also the standard for chat apps.
