### ISSUE TITLE
Link on :focus is invisible on dark mode

### ISSUE THREAD

**Issue by PatrickMatthiesen** [PhilipFlyvholm/learnit-plus-plus#23]
When a link is in focus it becomes black, which in dark mode makes it invisible.

**Comment by PhilipFlyvholm** [comment]
This is how it looks for me when in focus:
![image](https://github.com/PhilipFlyvholm/learnit-plus-plus/assets/36300927/c9c1cb62-a59c-45e0-bf0a-80e9767fb93e)

It ain't pretty but just to be sure that this is what you are referring to.

**Comment by PatrickMatthiesen** [comment]
Yup that is it
