### ISSUE TITLE
Add submission button goes out of bounds when window is halved

### ISSUE THREAD

**Issue by Pinkvinus** [PhilipFlyvholm/learnit-plus-plus#24]
When the window size decreases the add submission button goes outside the bounds of the timeline data block

![image](https://github.com/PhilipFlyvholm/learnit-plus-plus/assets/74830754/12dbc7c4-f9fc-416d-85ae-76efbea68008)

**Comment by PatrickMatthiesen** [comment]
It looks like it is happening if the window width is less than 1080xp
