### ISSUE TITLE
text can be hard to read in darkmode

### ISSUE THREAD

**Issue by Rasmus-Balthazar** [PhilipFlyvholm/learnit-plus-plus#34]
Darkmode integration with `student forum` makes text hard to read as the color of the text is changed to white while the background is white. See picture below for demonstration. I have marked part of the text that is supposed to be readable.

![image](https://github.com/PhilipFlyvholm/learnit-plus-plus/assets/74965526/92c59dd9-8382-4946-9d12-94c680ba5c9b)

Chrome extension tab text is hard to read: 
![image](https://github.com/PhilipFlyvholm/learnit-plus-plus/assets/74965526/0931e627-912f-4755-9ffc-68d7ebcfa7c9)

**Comment by lucasfth** [comment]
Will be fixed in #35
