### ISSUE TITLE
Bug: Opening a new tab removes themes from previously open tabs

### ISSUE THREAD

**Issue by PhilipFlyvholm** [PhilipFlyvholm/learnit-plus-plus#40]

**Comment by PhilipFlyvholm** [comment]
@PatrickMatthiesen Can you test if this is still a problem? A fix should be up on the main branch

**Comment by PatrickMatthiesen** [comment]
it does not work. From what I can see, duplicating the tab makes the previous pages stop functioning properly. But if i change the theme then all tabs open are updated to use the new theme, "fixing" the issue.

**Comment by PhilipFlyvholm** [comment]
How do you duplicate a tab? I tried with opening a new tab and it worked fine after the fix. Just to be sure, you are on the newest main?
