### ISSUE TITLE
Plugin options on chrome is miscolored

### ISSUE THREAD

**Issue by Rasmus-Balthazar** [PhilipFlyvholm/learnit-plus-plus#47]
When selecting and viewing the options for the plugin the colors are hard to distinguish as they are all very whiteish. This is on a windows computer in chrome. 

![image](https://github.com/PhilipFlyvholm/learnit-plus-plus/assets/74965526/3dd05a64-df36-4f0c-9a99-4fd85ca76501)

**Comment by Rasmus-Balthazar** [comment]
@PhilipFlyvholm Flyyyyv, det driller stadigvæk:(

**Comment by lucasfth** [comment]
I also saw it happen on a Linux machine.
I have been unable to see a correlation on what triggers the problem, as I could not replicate the problem on my machine.

**Comment by PhilipFlyvholm** [comment]
@Rasmus-Balthazar hvilken version bruger du og har du nogle andre extensions som gør noget dark mode relateret?

**Comment by PhilipFlyvholm** [comment]
These lines need to be removed: https://github.com/PhilipFlyvholm/learnit-plus-plus/blob/main/src/popup/index.css#L60C1-L71C2
