### ISSUE TITLE
Feat: Add lille kat events to LearnIT

### ISSUE THREAD

**Issue by PhilipFlyvholm** [PhilipFlyvholm/learnit-plus-plus#50]
https://lillekat.github.io/
This would require some more advanced scraping since they don't have an ID or class for the events.

**Comment by lucasfth** [comment]
Would it not be a better solution to ask SC if they could sync Lillekat events?

**Comment by PhilipFlyvholm** [comment]
This would also be a good idea. Without having talked to SC about it, I do think this could be because it is a faculty hosted event, and not a student hosted event. Therefor it would not be  part of SC.

**Comment by PhilipFlyvholm** [comment]
But we could take contact and maybe also address that scrollbar events are not part of SC's calendar.

**Comment by lucasfth** [comment]
I will talk to Shamal about it

**Comment by lucasfth** [comment]
Lille kat already has access to sync their events to SC events. I will talk to them about using it more frequently. No more work will be needed from us then.
