### ISSUE TITLE
Analog is closed

### ISSUE THREAD

**Issue by lucasfth** [PhilipFlyvholm/learnit-plus-plus#63]
Would it be possible to make it so that it says that Analog is closed (so that it takes vacations and exam periods into account)?

**Comment by PhilipFlyvholm** [comment]
Sure, we could add a list of closed days. However I don't know if there is a "smarter" way since the dates vary every year

**Comment by lucasfth** [comment]
> Sure, we could add a list of closed days. However I don't know if there is a "smarter" way since the dates vary every year

I will try to ask AnalogIO if a smarter way can be implemented

**Comment by PatrickMatthiesen** [comment]
any news on this?

**Comment by lucasfth** [comment]
Unfortunately, I am not getting a response. But since the dates vary every year as Philip pointed out, it seems to be a lot of extra work to keep updating the dates often.
