### ISSUE TITLE
Student Council Events link icon is weirdly placed

### ISSUE THREAD

**Issue by PatrickMatthiesen** [PhilipFlyvholm/learnit-plus-plus#66]
With a short tile that fits the box, the icon is pushed to the right by a large margin-right:
![image](https://github.com/PhilipFlyvholm/learnit-plus-plus/assets/43612965/2ce1b128-b359-49ba-9ea3-02537ea245e8)

And when the tile is long the text wrap makes the issue kinda worse:
![image](https://github.com/PhilipFlyvholm/learnit-plus-plus/assets/43612965/30708f4c-58c9-4d53-9918-62f24ef342a4)

**Comment by PhilipFlyvholm** [comment]
By removing the right margin it should fix the problem for small titles, but would not be a perfect fix for longer titles
