### ISSUE TITLE
[BUG] Table coloring messed up for darkmode

### ISSUE THREAD

**Issue by Grymse** [PhilipFlyvholm/learnit-plus-plus#70]
On My Courses -> Table of courses are a bit broken in darkmode.

I have included the exact CSS variable that needs to be changed in the image

<img width="1512" alt="image" src="https://github.com/PhilipFlyvholm/learnit-plus-plus/assets/26344425/89bbdbfa-0a3c-4184-b111-f4b2e67de34e">

**Comment by PhilipFlyvholm** [comment]
Fixed in next release: https://github.com/PhilipFlyvholm/learnit-plus-plus/commit/7f505710d18c8b70ce935ceb6220f57ae4bc391d
