### ISSUE TITLE
Pagination does not respect Dark Mode

### ISSUE THREAD

**Issue by Pinkvinus** [PhilipFlyvholm/learnit-plus-plus#9]
The page selection element on the "All courses" page seems to not be in darkmode.
![image](https://github.com/PhilipFlyvholm/learnit-plus-plus/assets/74830754/ecd96eca-3db1-43d8-90c6-67a0a5e40eb8)

**Comment by PatrickMatthiesen** [comment]
what looks better?

1. 
![image](https://github.com/PhilipFlyvholm/learnit-plus-plus/assets/43612965/64fafb4d-1f92-4891-b6aa-bc4c8d5cea0b)
--pagination-bg-color: var(--page-bg-color);
--pagination-border-color: var(--page-fg-color);

2.
![image](https://github.com/PhilipFlyvholm/learnit-plus-plus/assets/43612965/b9aefc71-96e6-4052-917d-0ae32f8ee8f5)
--pagination-bg-color: var(--card-bg-color);
--pagination-border-color: var(--card-border-color);

3.
![image](https://github.com/PhilipFlyvholm/learnit-plus-plus/assets/43612965/6104d5a0-2036-4fd1-8c20-7ba1d7c00019)
--pagination-bg-color: less black;
border: none;

4.
![image](https://github.com/PhilipFlyvholm/learnit-plus-plus/assets/43612965/25d372bd-a7cd-4a2e-a738-d9ef4332889a)
--pagination-bg-color: black;
--pagination-border-color: var(--page-border-color);

5.
![image](https://github.com/PhilipFlyvholm/learnit-plus-plus/assets/43612965/be8ec11c-75e3-48a1-bacf-f1c2211d8c17)
--pagination-bg-color: #333;
--pagination-border-color: #6a737b;
border-left: none;

**Comment by PhilipFlyvholm** [comment]
2. and 3. are very clean. 2. looks more like LearnIT design so I would recommend it
